### PR TITLE
submission pr

### PR DESCRIPTION
**Pull request by belyaev249**
buy/sell, swap, staking
tm @bvbvbvch

### CODE REVIEW

**Comment by VishalBheelkumar** [comment]
belyaev249:contest

**Comment by kyawzinoo4** [comment]
belyaev249:contest

**Comment by bilalelghazlani** [comment]
Can yuo hiiipe meee

**Comment by seedasadsadgey** [comment]
> buy/sell, swap, staking
> tm @VishalBheelkumar 
>

**Pull request closed without merging**
